# Generated by Django 4.2.8 on 2025-11-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('pergunta', 'Pergunta'), ('resposta', 'Resposta')], default='resposta', max_length=50),
        ),
    ]
